### PR TITLE
Add support for site & add docs & refactors & cleanup

### PR DESCRIPTION
**Pull request by mhdzumair**
## Summary by CodeRabbit

- **New Features**
  - Added more non-English character support for title parsing.
  
- **Refactor**
  - Improved type hints and readability for various functions including `extend_options`, `create_handler_from_regexp`, `clean_title`, and `Parser` class methods.
  
- **Tests**
  - Updated and added test cases to ensure robustness and accuracy in title parsing, including new tests for site and size detection.

### CODE REVIEW

**Comment by dreulavelle** [comment]
I've changed so much stuff on my own, as I was also working on a large commit lol. I've taken a lot of stuff out as well from here as I had already started working on it before the PR.

How are things running for you currently though? I am currently adding more handlers as well

**Comment by mhdzumair** [comment]
Cool. I'm almost done with the changes and ready to release the changes for MediaFusion. Its working great. There are some slightly off case scenarios like typos in the naming conventions,
 ex: 
 ```
"www,1TamilMV.phd - The Great Indian Suicide (2023) Tamil TRUE WEB-DL - 4K SDR - HEVC - (DD+5.1 - 384Kbps & AAC) - 3.2GB - ESub.mkv"
"ww.Tamilblasters.sbs - 8 Bit Christmas (2021) HQ HDRip - x264 - Telugu (Fan Dub) - 400MB].mkv"
"www.1TamilMV.pics - 777 Charlie (2022) Tamil HDRip - 720p - x264 - HQ Clean Aud - 1.4GB.mkv"
```

1, 2 having typos in the URL. But 3rd one, not sure what's wrong with. The title should be `777 Charlie` however it's parsing as '777 Charlie  Tamil  -  -  -  - .'

**Comment by dreulavelle** [comment]
image

Ah yes, I can work on these

**Comment by dreulavelle** [comment]
alright I've merged my changes and changes from this into main, so we should be roughly on the same page now

**Comment by dreulavelle** [comment]
If I missed something, just submit a new PR. I'll handle the next PR better lol. Apologies!

**Comment by dreulavelle** [comment]
I do have more stuff coming possibly as I'm trying to migrate _some_ things from PTN over to this so that we can support everything. I've gotta work on RTN changes now, I have a large update coming for that as well.

**Pull request closed without merging**
